### ISSUE TITLE
Integrate repository with a CI environment

### ISSUE THREAD

**Issue by mpeuster** [5gtango/tango-schema#2]

**Comment by felipevicens** [comment]
Hey @mpeuster, what do you have in mind? Do we need a new Jenkins for this?

**Comment by mpeuster** [comment]
Hi @felipevicens it's just simple validation of schemas / examples in this repo when we re-design the descriptors. My idea was just to use Travis-CI for now. Maybe switch when we have a clear Jenkins strategy / setup for TANGO.

**Comment by jbonnet** [comment]
Or... keep Travis-CI!Why not? It costs us precious Felipe's mibutes to maintain Jenkins...José Em 13/10/2017 17:05, peusterm <notifications@github.com> escreveu:Hi @felipevicens it's just simple validation of schemas / examples in this repo when we re-design the descriptors. My idea was just to use Travis-CI for now. Maybe switch when we have a clear Jenkins strategy / setup for TANGO.

**Comment by felipevicens** [comment]
Exactly @jbonnet @mpeuster I was planning to leave some easy jobs in hands of travis.  But not for all. This is a good candidate for travis.  I remember the only disadvantage was the time wait until travis is triggered for the tests. Maybe @mpeuster you know how is going it now because containernet project. Is it better now?

**Comment by mpeuster** [comment]
Good morning, I absolutely agree that we should use Travis where possible. I just was not sure if you prefer Jenkins instead ;-) We go for Travis then.

My experience from containernet shows that it works very smoothly. Even though containernet is a relative heavy job. And you are even allowed to have periodic (daily, weekly, ...) builds in addition to the PR builds now.  Did not have any issues with it in the last year.

**Comment by mpeuster** [comment]
Integration is done. All old tests from SONATA are now executed by travis for this repository: https://travis-ci.org/5gtango/tango-schema
